<a href="https://colab.research.google.com/github/s1scottd/ColabStorage/blob/main/first_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
from tensorflow import keras
from keras.datasets import mnist
from keras import layers
 
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

print(train_images.ndim)
print(train_images.shape)
print(train_images.dtype)
print(len(train_labels))
print(train_labels)

print(test_images.ndim)
print(test_images.shape)
print(test_images.dtype)
print(len(test_labels))
print(test_labels)

model = keras.Sequential([layers.Dense(512, activation="relu"), layers.Dense(10, activation="softmax")])

model.compile(optimizer="rmsprop", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32")/255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32")/255

print(train_images.ndim)
print(len(train_labels))
print(train_labels)
print(train_images.shape)
print(train_images.dtype)
print(test_images.ndim)
print(len(test_labels))
print(test_labels)
print(test_images.shape)
print(test_images.dtype)

model.fit(train_images, train_labels,epochs=5, batch_size=128)

3
(60000, 28, 28)
uint8
60000
[5 0 4 ... 5 6 8]
3
(10000, 28, 28)
uint8
10000
[7 2 1 ... 4 5 6]
2
60000
[5 0 4 ... 5 6 8]
(60000, 784)
float32
2
10000
[7 2 1 ... 4 5 6]
(10000, 784)
float32
Epoch 1/5
469/469 [==============================] - 5s 10ms/step - loss: 0.2647 - accuracy: 0.9247
Epoch 2/5
469/469 [==============================] - 7s 14ms/step - loss: 0.1074 - accuracy: 0.9687
Epoch 3/5
469/469 [==============================] - 6s 12ms/step - loss: 0.0693 - accuracy: 0.9789
Epoch 4/5
469/469 [==============================] - 6s 12ms/step - loss: 0.0504 - accuracy: 0.9847
Epoch 5/5
469/469 [==============================] - 6s 13ms/step - loss: 0.0374 - accuracy: 0.9890


In [16]:
# Make a prediction
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
print(predictions[0])
print(predictions[0].argmax())
print(predictions[0][7])

1/1 [==============================] - 0s 56ms/step
[5.6031602e-08 2.2565558e-09 2.9937635e-06 1.3585661e-05 1.8452499e-12
 2.5010321e-08 1.5333328e-12 9.9998242e-01 1.1172301e-08 8.7826476e-07]
7
0.9999824


In [17]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc:{test_acc}")

313/313 [==============================] - 1s 3ms/step - loss: 0.0594 - accuracy: 0.9810
test_acc:0.9810000061988831
